"""ACP v2 conformance layer for the WebSocket signal bridge.

Provides data classes, JSON-RPC message builders, inbound dispatch,
and signal-to-ACP notification translators that bridge the existing
blinker-signal IO system to the Agent Client Protocol v2 JSON-RPC format.
"""

from cecli.helpers.server.acp.bridge import (
    AcpSignalBridge,
    ReasoningTracker,
    make_message_id,
    make_tool_call_id,
)
from cecli.helpers.server.acp.models import (
    AgentCapabilities,
    AgentMessageChunk,
    AgentMessageUpdate,
    AgentThoughtChunk,
    AgentThoughtUpdate,
    ContentBlock,
    ContentBlockResource,
    ContentBlockText,
    ImplementationInfo,
    InitializeParams,
    InitializeResult,
    JsonRpcError,
    JsonRpcRequest,
    JsonRpcResponse,
    SessionCancelParams,
    SessionCapabilities,
    SessionCloseParams,
    SessionInfo,
    SessionListResult,
    SessionNewParams,
    SessionNewResult,
    SessionPromptParams,
    SessionPromptResult,
    SessionResumeParams,
    StateUpdate,
    ToolCallContentChunk,
    ToolCallUpdate,
    UserMessageChunk,
    UserMessageUpdate,
)
from cecli.helpers.server.acp.protocol import (
    build_error_response,
    build_notification,
    build_request,
    build_response,
    dispatch_inbound,
    make_agent_message_chunk,
    make_agent_thought_chunk,
    make_initialize_result,
    make_session_list_result,
    make_session_new_result,
    make_session_update_notification,
    make_state_update,
    make_tool_call_content_chunk,
    make_tool_call_update,
    make_user_message,
    parse_message,
)

__all__ = [
    # Bridge
    "AcpSignalBridge",
    "ReasoningTracker",
    "make_message_id",
    "make_tool_call_id",
    # Models
    "AgentCapabilities",
    "AgentMessageChunk",
    "AgentMessageUpdate",
    "AgentThoughtChunk",
    "AgentThoughtUpdate",
    "ContentBlock",
    "ContentBlockResource",
    "ContentBlockText",
    "InitializeParams",
    "InitializeResult",
    "ImplementationInfo",
    "JsonRpcError",
    "JsonRpcRequest",
    "JsonRpcResponse",
    "SessionCancelParams",
    "SessionCapabilities",
    "SessionCloseParams",
    "SessionInfo",
    "SessionListResult",
    "SessionNewParams",
    "SessionNewResult",
    "SessionPromptParams",
    "SessionPromptResult",
    "SessionResumeParams",
    "StateUpdate",
    "ToolCallContentChunk",
    "ToolCallUpdate",
    "UserMessageChunk",
    "UserMessageUpdate",
    # Protocol
    "build_error_response",
    "build_notification",
    "build_request",
    "build_response",
    "dispatch_inbound",
    "make_agent_message_chunk",
    "make_agent_thought_chunk",
    "make_initialize_result",
    "make_session_list_result",
    "make_session_new_result",
    "make_session_update_notification",
    "make_state_update",
    "make_tool_call_content_chunk",
    "make_tool_call_update",
    "make_user_message",
    "parse_message",
]
