[pytest]
norecursedirs = tmp.* build benchmark _site OLD
addopts = -p no:warnings
asyncio_mode = auto
testpaths =
    tests/basic
    tests/tools
    tests/coders
    tests/subagents
    tests/commands
    tests/conversations
    tests/helpers
    tests/hooks
    tests/integration
    tests/mcp
    tests/help
    tests/tui
    tests/unit
    tests/scrape
    tests/test_requests.py

env =
    CECLI_TUI=false
