# flake8: noqa: F401
# Import tool modules into the cecli.tools namespace

from . import (
    _yield,
    broadcast,
    command,
    delegate,
    edit_file,
    explore_code,
    git_branch,
    git_diff,
    git_log,
    git_remote,
    git_show,
    git_status,
    grep,
    ls,
    orchestrate,
    read_file,
    replace_facts,
    resource_manager,
    search_facts,
    thinking,
    undo_change,
    update_todo_list,
)

# List of all available tool modules for dynamic discovery
TOOL_MODULES = [
    command,
    delegate,
    edit_file,
    explore_code,
    _yield,
    broadcast,
    git_branch,
    git_diff,
    git_log,
    git_remote,
    git_show,
    git_status,
    grep,
    ls,
    orchestrate,
    read_file,
    replace_facts,
    resource_manager,
    search_facts,
    thinking,
    undo_change,
    update_todo_list,
]
